baseURL = "https://example.com"
title = "Hugo Blog"
description = "A description"
canonifyURLs = true
enableRobotsTXT = true
paginate = 10
paginatePath = ''

[params]
  dateFormat = "Jan 2, 2006"
  name = "Edoardo D'Angelis"
  bio = "MSc Computer Engineering [@UNIFI](https://unifi.it)"
  image = "https://avatars.githubusercontent.com/u/11541888?v=4"

  [[params.work]]
    from = "Jun 2021"
    to = "Present"
    title = "Software Engineer @ [Magenta](https://magentalab.it)"
    additionalText = """
- AirQuino backend management using Java + Spring
- Optimizing performance of time-series database (Timescale) queries by 10x using continuous aggregates
- Studying machine learning models to improve batch sensors calibration
  """

  [[params.education]]
    from = "Sep 2019"
    to = "?"
    title = "Master's degree in Computer Science & Engineering"
    additionalText = "soon"
  [[params.education]]
    from = "Sep 2015"
    to = "Apr 2019"
    title = "Bachelor's degree in Computer Science & Engineering"
    additionalText = "**Thesis:** _Semantic expansion of bibliographic records_: using ML-based entity extraction tools and SPARQL queries to generate semantic annotations based on geographic data"
    where = "Università degli Studi di Firenze, Florence, Italy"
  [[params.education]]
    from = "Jun 2015"
    title = "Secondary school diploma"
    additionalText = "**Thesis:** _Bitcoin: the currency of the future?_"
    where = "Liceo Scientifico _Guido Castelnuovo_, Florence, Italy"


[sitemap]
    changefreq = "weekly"
    priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "home"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    pre = "hashtag"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
    pre = "pencil"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "about"
  
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/n3d1117/"
    weight = 1
    pre = "github"
  [[menu.social]]
    name = "Telegram"
    url = "https://t.me/ne_do/"
    weight = 2
    pre = "telegram"
  [[menu.social]]
    name = "Email"
    url = "mailto:your.email@me.com"
    weight = 3
    pre = "mail"
  [[menu.social]]
    name = "Donate"
    url = "https://www.buymeacoffee.com/ne_do"
    weight = 4
    pre = "heart"
  [[menu.social]]
    name = "RSS"
    url = "/feed.rss"
    weight = 5
    pre = "rss"

  [[menu.about]]
    name = "About"
    url = "/about/"
    weight = 1
    pre = "about"
  [[menu.about]]
    name = "Movies"
    url = "/about/movies/"
    weight = 2
    pre = "robot"
  [[menu.about]]
    name = "TV Shows"
    url = "/about/shows/"
    weight = 3
    pre = "video"
  [[menu.about]]
    name = "Books"
    url = "/about/books/"
    weight = 4
    pre = "book"
  [[menu.about]]
    name = "Music"
    url = "/about/music/"
    weight = 5
    pre = "music"

[markup]
  [markup.highlight]
    noClasses = false

[build]
  writeStats = true