baseURL = "https://example.com"
title = "Hugo Blog"
description = "A description"
canonifyURLs = true
enableRobotsTXT = true
paginate = 10
paginatePath = ''


[params]
  dateFormat = "Jan 2, 2006"
  name = "Edoardo D'Angelis"
  bio = "MSc Computer Engineering [@UNIFI](https://unifi.it)"
  image = "https://avatars.githubusercontent.com/u/11541888?v=4"

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "home"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    pre = "hashtag"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
    pre = "pencil"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "about"
  
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/n3d1117/"
    weight = 1
    pre = "github"
  [[menu.social]]
    name = "Telegram"
    url = "https://t.me/ne_do/"
    weight = 2
    pre = "telegram"
  [[menu.social]]
    name = "Email"
    url = "mailto:your.email@me.com"
    weight = 3
    pre = "mail"
  [[menu.social]]
    name = "Donate"
    url = "https://www.buymeacoffee.com/ne_do"
    weight = 4
    pre = "heart"
  [[menu.social]]
    name = "RSS"
    url = "/feed.rss"
    weight = 5
    pre = "rss"

[markup]
  [markup.highlight]
    noClasses = false

[build]
  writeStats = true