baseURL = "https://example.com"
title = "Hugo Blog"
description = "A description"
canonifyURLs = true
copyright = "Name"
enableRobotsTXT = true

paginate = 10
paginatePath = ''

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"

[markup]
  [markup.highlight]
    noClasses = false

[build]
  writeStats = true