baseURL = "https://edoardo.fyi/"
title = "Edoardo D'Angelis"
description = "Software Engineer"
enableRobotsTXT = true
paginate = 15
paginatePath = ''
copyright = "© Edoardo D'Angelis — All rights reserved"
languageCode = "en-us"
disableHugoGeneratorInject = true

[author]
  name = "Edoardo D'Angelis"
  email = "contact@edoardo.fyi"

[params]
  dateFormat = "Jan 2, 2006"
  name = "Edoardo D'Angelis"
  bio = "Software Engineer [@Magenta](https://magentalab.it)"
  loc = "Florence, Italy"
  image = "/me.jpeg"
  images = ["me.jpeg"]

  [[params.work]]
    from = "February 2022"
    to = "present"
    title = "Software Engineer @ [Magenta](https://magentalab.it)"
    additionalText = """
- Refactoring the [GreenApes](https://www.greenapes.com)  iOS App using [Swift](https://www.swift.org), [SwiftUI](https://developer.apple.com/xcode/swiftui/) and [Combine](https://developer.apple.com/documentation/combine)
- Writing Java backend microservices using [Quarkus](https://quarkus.io) and [Apache Kafka](https://kafka.apache.org)
- Building reactive web applications using [Angular](https://angular.io) and [NgRx](https://ngrx.io)
"""

  [[params.work]]
    from = "September 2021"
    to = "January 2022"
    title = "Software Engineering Internship @ [Magenta](https://magentalab.it)"
    additionalText = """
- Enhanced the [AirQino](https://www.airqino.it/en/) stations calibration process through regression models with advanced robust techniques based on previous historical data
- Maximized performance of [Timescale](https://www.timescale.com) queries using [continuous aggregates](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/), significantly reducing response times of the [AirQino](https://www.airqino.it/en/) backend APIs
- Set up a 1:1 read-only [streaming replica](https://wiki.postgresql.org/wiki/Streaming_Replication) of the primary [AirQino](https://www.airqino.it/en/) database (>100M rows) for performance tests, relieving the load on the primary database and increasing availability
  """

  [[params.education]]
    from = "September 2019"
    to = "April 2022"
    title = "MSc in Computer Science & Engineering"
    where = "[University of Florence](https://unifi.it), Italy 🇮🇹"
    additionalText = """
- **Final grade:** `110/110` with honours
- **Thesis:** Design and development of components for the [AirQino](https://www.airqino.it/en/) platform dedicated to air quality monitoring 
- **Relevant courses:** Software Architectures and Methodologies, Big Data Architectures, Advanced Programming Techniques, Parallel Computing, Human Computer Interaction
"""
  [[params.education]]
    from = "September 2015"
    to = "April 2019"
    title = "BSc in Computer Science & Engineering"
    additionalText = """
- **Thesis:** _Semantic expansion of bibliographic records_: using ML-based entity extraction tools (such as [spaCy](https://spacy.io)) and [SPARQL](https://www.w3.org/TR/rdf-sparql-query/) queries to generate annotations based on geographic data.
- **Relevant courses:** Algorithms and Data Structures, Operating Systems, Artificial Intelligence, Databases, Software Engineering
"""
    where = "[University of Florence](https://unifi.it), Italy 🇮🇹"
  [[params.education]]
    from = "June 2015"
    title = "Secondary school diploma"
    additionalText = """
- **Thesis:** _Bitcoin: the currency of the future?_
"""
    where = "Liceo Scientifico [_Guido Castelnuovo_](https://www.liceocastelnuovo.edu.it), Florence, Italy 🇮🇹"

[sitemap]
    changefreq = "monthly"
    priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "home"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    pre = "hashtag"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "about"
  
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/n3d1117/"
    weight = 1
    pre = "github"
  [[menu.social]]
    name = "Mastodon"
    url = "https://mastodon.social/@nedo/"
    weight = 2
    pre = "mastodon"
  [[menu.social]]
    name = "Email"
    url = "mailto:contact@edoardo.fyi"
    weight = 3
    pre = "mail"
  [[menu.social]]
    name = "Donate"
    url = "https://www.buymeacoffee.com/ne_do"
    weight = 4
    pre = "heart"
  [[menu.social]]
    name = "RSS"
    url = "feed://edoardo.fyi/blog/index.xml"
    weight = 5
    pre = "rss"

  [[menu.about]]
    name = "About"
    url = "/about/"
    weight = 1
    pre = "about"
  [[menu.about]]
    name = "Movies"
    url = "/about/movies/"
    weight = 2
    pre = "robot"
  [[menu.about]]
    name = "TV Shows"
    url = "/about/shows/"
    weight = 3
    pre = "video"
  [[menu.about]]
    name = "Books"
    url = "/about/books/"
    weight = 4
    pre = "book"
  [[menu.about]]
    name = "Music"
    url = "/about/music/"
    weight = 5
    pre = "music"
  [[menu.about]]
    name = "Games"
    url = "/about/games/"
    weight = 6
    pre = "games"

[markup]
  [markup.highlight]
      lineNos = true
      lineNumbersInTable = true
      noClasses = false

[outputs]
    page = ["HTML"]
    home = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]