baseURL = "https://example.com"
title = "Hugo Blog"
description = "A description"
enableRobotsTXT = true
paginate = 10
paginatePath = ''
copyright = "© Edoardo D'Angelis — All rights reserved"
languageCode = "en-us"

[author]
  name = "Edoardo D'Angelis"

[params]
  dateFormat = "Jan 2, 2006"
  name = "Edoardo D'Angelis"
  bio = "Software Engineer [@Magenta](https://magentalab.it)"
  image = "/me.jpeg"

  [[params.work]]
    from = "September 2021"
    to = "present"
    title = "Software Engineer @ [Magenta](https://magentalab.it)"
    additionalText = """
- Trained machine learning models to improve batch sensors calibration
- Built a sensors calibration dashboard for [AirQino](https://www.airqino.it/en/) project
- Optimized performance of [Timescale](https://www.timescale.com) queries by 10x using techniques such as [continuous aggregates](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/)
- Set up a 1:1 read-only streaming replica of the primary database (>60M rows) for performance tests, offloading heavy queries and availability
  """

  [[params.education]]
    from = "September 2019"
    to = "April 2022"
    title = "MSc in Computer Science & Engineering"
    where = "[University of Florence](https://unifi.it), Italy 🇮🇹"
    additionalText = """
- **Thesis:** Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
- **Final grade:** `110/110`
- **Relevant courses:** Big Data Architectures, Advanced Programming Techniques, Parallel Computing, Software Engineering for Embedded Systems, Penetration Testing, Human Computer Interaction, Software Architectures and Methodologies
"""
  [[params.education]]
    from = "September 2015"
    to = "April 2019"
    title = "BSc in Computer Science & Engineering"
    additionalText = """
- **Thesis:** _Semantic expansion of bibliographic records_: using ML-based entity extraction tools (such as [spaCy](https://spacy.io)) and [SPARQL](https://www.w3.org/TR/rdf-sparql-query/) queries to generate semantic annotations based on geographic data.
- **Relevant courses:** Algorithms and Data Structures, Operating Systems, Databases, Software Engineering, Artificial Intelligence, Multimedia Design and Production, Telecommunication Networks
"""
    where = "[University of Florence](https://unifi.it), Italy 🇮🇹"
  [[params.education]]
    from = "June 2015"
    title = "Secondary school diploma"
    additionalText = """
- **Thesis:** _Bitcoin: the currency of the future?_
- Implemented the (now defunct) school newspaper website called *DeGeneratione*, [still available](https://web.archive.org/web/20160217175239/https://degeneratione.it/) on the Wayback Machine
"""
    where = "Liceo Scientifico [_Guido Castelnuovo_](https://www.liceocastelnuovo.edu.it), Florence, Italy 🇮🇹"


[sitemap]
    changefreq = "weekly"
    priority = 0.5

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  page = "/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "home"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
    pre = "hashtag"
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    pre = "about"
  
  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/n3d1117/"
    weight = 1
    pre = "github"
  [[menu.social]]
    name = "Telegram"
    url = "https://t.me/ne_do/"
    weight = 2
    pre = "telegram"
  [[menu.social]]
    name = "Email"
    url = "mailto:your.email@me.com"
    weight = 3
    pre = "mail"
  [[menu.social]]
    name = "Donate"
    url = "https://www.buymeacoffee.com/ne_do"
    weight = 4
    pre = "heart"
  [[menu.social]]
    name = "RSS"
    url = "/blog/index.xml"
    weight = 5
    pre = "rss"

  [[menu.about]]
    name = "About"
    url = "/about/"
    weight = 1
    pre = "about"
  [[menu.about]]
    name = "Movies"
    url = "/about/movies/"
    weight = 2
    pre = "robot"
  [[menu.about]]
    name = "TV Shows"
    url = "/about/shows/"
    weight = 3
    pre = "video"
  [[menu.about]]
    name = "Books"
    url = "/about/books/"
    weight = 4
    pre = "book"
  [[menu.about]]
    name = "Music"
    url = "/about/music/"
    weight = 5
    pre = "music"

[markup]
  [markup.highlight]
    noClasses = false

[outputs]
    page = ["HTML"]
    home = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]