baseURL = "https://example.com"
title = "Hugo Blog"

[taxonomies]
  tag = "tags"

[permalinks]
  blog = "/blog/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"